#home:
#   path: /
#   controller: App\Controller\HomeController::index

#property:
 #  path: /biens
  # controller: App\Controller\PropertyController::property.index
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
