home:
   path: /
   controller: App\Controller\HomeController::index

property:
   path: /
   controller: App\Controller\PropertyController::property
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
